export enum USER_SOCKETS_TYPE {

    USERS_COLUMNS = 'USERS_COLUMNS',
    USERS_FIND_ALL = 'USERS_FIND_ALL',
    USERS_FIND_ONE = 'USERS_FIND_ONE',
    USERS_UPDATE = 'USERS_UPDATE',
    USERS_DELETE = 'USERS_DELETE',
}